name: Deploy test server sit

on:
  push:
    branches: ['dev']
  workflow_dispatch:

env:
  KEY: sit  # 全局定义 KEY 环境变量
  ECR_REGISTRY: 147997140725.dkr.ecr.ap-southeast-1.amazonaws.com  # 全局定义 ECR_REGISTRY
  ECR_REPOSITORY: sit/bitbot/test  # 全局定义 ECR_REPOSITORY
  IMAGE_TAG: test-${{ github.sha }}-${{ github.run_id }}  # 全局定义 IMAGE_TAG

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: "dev"
      - name: Print current branch
        run: |
            current_branch=$(git branch --show-current)
            echo "Current checked out branch: $current_branch"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}  # 使用全局环境变量
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}  # 使用全局环境变量
          IMAGE_TAG: ${{ env.IMAGE_TAG }}  # 使用全局环境变量
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-to-eks:
    needs: [build-and-push]
    name: Deploy to EKS
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "dev"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install kubectl
        run: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/kubectl

      - name: Configure AWS CLI for EKS
        run: |
             aws eks --region ap-southeast-1 update-kubeconfig --name bitbot-${{ env.KEY }}-eks

      - name: Update eks
        run: |
          sed -i "s|<IMAGE_PLACEHOLDER>|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" k8s.yaml

          # Apply the updated deployment configuration
          kubectl -n ${{ env.KEY }} apply -f k8s.yaml  # 使用全局环境变量 KEY
