name: fast-forward
on:
  issue_comment:
    types: [created, edited]
jobs:
  fast-forward:
    # Only run if the comment contains the /fast-forward command.
    if: ${{ contains(github.event.comment.body, '/fast-forward')
            && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR target branch
        run:
          echo "The target branch is: ${{ github.event.pull_request.base.ref }}"
      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          # To reduce the workflow's verbosity, use 'on-error'
          # to only post a comment when an error occurs, or 'never' to
          # never post a comment.  (In all cases the information is
          # still available in the step's summary.)
          comment: always
  ci_cd:
    runs-on: ubuntu-latest
    needs: fast-forward
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Trigger appropriate deployment workflow
        env:
          GH_TOKEN: ${{ github.token }}  # 设置 GH_TOKEN 环境变量
          PR_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          echo "${PR_BRANCH}"
          if [[ "${PR_BRANCH}" == "dev" ]]; then
            echo "Triggering deployment for dev branch"
            # 调用 dev 环境部署的 workflow
            gh workflow run deploy-main-bot-sit.yml
          elif [[ "${PR_BRANCH}" == "main" ]]; then
            echo "Triggering deployment for main branch"
            # 调用PROD 环境部署的 workflows
            gh workflow run deploy-main-bot-prod.yml
          else
            echo "This is neither the dev nor main branch. Skipping deployment."
          fi



