name: fast-forward

on:
  issue_comment:
    types: [created, edited]

jobs:
  fast-forward:
    if: ${{ contains(github.event.comment.body, '/fast-forward') && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      head_ref: ${{ steps.comment-branch.outputs.head_ref }}
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - name: Get PR target branch
        run: |
            echo "The target branch is: ${{ steps.comment-branch.outputs.head_ref }}"

      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          comment: always
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

