name: fast-forward

on:
  issue_comment:
    types: [created, edited]

jobs:
  fast-forward:
    if: ${{ contains(github.event.comment.body, '/fast-forward') && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR target branch
        id: get_target_branch
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          if [ "$branch_name" == "main" ]; then
          # 主分支流程
          echo "Running main branch specific process"
          # 在这里添加主分支的具体命令，例如构建、部署等
          elif [ "$branch_name" == "develop" ]; then
          # develop分支流程
          echo "Running develop branch specific process"
          # 在这里添加develop分支的具体命令
          else
          # 其他分支流程
          echo "Running other branches specific process"
          # 在这里添加其他分支的具体命令
          fi

      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          comment: always

  ci_cd:
    runs-on: ubuntu-latest
    needs: fast-forward
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger appropriate deployment workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BRANCH: ${{ needs.get-target-branch.outputs.target-branch }}
        run: |
          if [[ "${github.event.pull_request.base.ref}" == "dev" ]]; then
            echo "Triggering deployment for dev branch"
            gh workflow run deploy-main-bot-sit.yml
          elif [[ "${github.event.pull_request.base.ref}" == "main" ]]; then
            echo "Triggering deployment for main branch"
            gh workflow run deploy-main-bot-prod.yml
          else
            echo "This is neither the dev nor main branch. Skipping deployment."
