name: fast-forward

on:
  issue_comment:
    types: [created, edited]

jobs:
  fast-forward:
    if: ${{ contains(github.event.comment.body, '/fast-forward') && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      target_branch: ${{ steps.get_target_branch.outputs.target_branch }}

    steps:
      - name: Get PR target branch
        id: get_target_branch
        run: |
          TARGET_BRANCH="${{ github.event.issue.pull_request.base.ref }}"
          echo "TARGET_BRANCH=${TARGET_BRANCH}" >> $GITHUB_ENV
          echo "target_branch=${TARGET_BRANCH}" >> $GITHUB_OUTPUT

      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          comment: always

  ci_cd:
    runs-on: ubuntu-latest
    needs: fast-forward
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger appropriate deployment workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BRANCH: ${{ needs.fast-forward.outputs.target_branch }}
        run: |
          echo "Target branch: ${PR_BRANCH}"
          if [[ "${PR_BRANCH}" == "dev" ]]; then
            echo "Triggering deployment for dev branch"
            gh workflow run deploy-main-bot-sit.yml
          elif [[ "${PR_BRANCH}" == "main" ]]; then
            echo "Triggering deployment for main branch"
            gh workflow run deploy-main-bot-prod.yml
          else
            echo "This is neither the dev nor main branch. Skipping deployment."
