name: fast-forward

on:
  issue_comment:
    types: [created, edited]

jobs:
  fast-forward:
    if: ${{ contains(github.event.comment.body, '/fast-forward') && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      # 输出目标分支
      target_branch: ${{ steps.get-target-branch.outputs.target_branch }}
    steps:
      - name: Get PR target branch
        id: get-target-branch
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const targetBranch = pullRequest.base.ref;
            core.setOutput('target_branch', targetBranch);
            console.log(`The target branch is: ${targetBranch}`);

      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          comment: always

  ci_cd:
    runs-on: ubuntu-latest
    needs: fast-forward
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger appropriate deployment workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BRANCH: ${{ needs.fast-forward.outputs.target_branch }}
        run: |
          if [[ "${{ needs.fast-forward.outputs.target_branch }}" == "dev" ]]; then
            echo "Triggering deployment for dev branch"
            gh workflow run deploy-main-bot-sit.yml
          elif [[ "${{ needs.fast-forward.outputs.target_branch }}" == "main" ]]; then
            echo "Triggering deployment for main branch"
            gh workflow run deploy-main-bot-prod.yml
          else
            echo "This is neither the dev nor main branch. Skipping deployment."
          fi